apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'CI Python 3.9 Build'
description: 'CI Python 3.9 Build'

# inputs:
#   context:
#     description: 'Python build context'
#     default: ${{ cloudbees.workspace }}
#   build-args:
#     description: 'Python build arguments'
#     required: false
#     default: ''

runs:
  using: composite
  steps:
    - id: ci-python3.9
      uses: docker://python:3.9-alpine
      shell: sh
      run: | 
        python3 --version

    - id: python3.9-requirements-install
      uses: docker://python:3.9-alpine
      shell: sh
      run: | 
        python3 --version

    - id: python3.9-test
      uses: docker://python:3.9-alpine
      shell: sh
      run: | 
        python3 --version

    # - id: checkmarx
    #   uses: cloudbees-io/checkmarx
    #   with:
    #       serverURL: "Checkmarx serverURL"
    #       username: "Checkmarx username"
    #       password: "Checkmarx password"
    #       token: ${{ secrets.CHECKMARX_SECRET }}
    #       language: "LANGUAGE_YOURCODELANGUAGE"

    # - id: sonarqube
    #   uses: cloudbees-io/sonarqube
    #   with:
    #       serverURL: "SonarQube server URL"
    #       username: "SonarQube username"
    #       password: "SonarQube password"
    #       language: "LANGUAGE_YOURCODELANGUAGE"

    - name: Write docker config.json
      uses: docker://alpine:3.18
      env:
        DOCKERCONFIGJSON: ${{ inputs.DOCKER-CONFIG }}
      run: | 
        mkdir -p $HOME/.docker
        echo "$DOCKERCONFIGJSON" > $HOME/.docker/config.json
        cat $HOME/.docker/config.json

    - id: kaniko
      uses: cloudbees-io/kaniko
      with:
          dockerfile: ${{ inputs.DOCKERFILE }}
          context: ${{ inputs.CONTEXT }}
          destination: ${{ inputs.KANIKO-DESTINATION }}
          build-args: ${{ inputs.KANIKO-BUILD-ARGS }}
          labels: ${{ inputs.KANIKO-LABELS }}